dist: xenial
language: python
os: linux
cache: pip
python:
  - 3.7
services:
  - postgresql
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
script:
  - ./runtests.sh
